language: java
jdk:
 - openjdk8

#master 브랜치에 push될 때만 수행
branches:
 only:
  - master

# Travis CI 서버의 Home
## Gradle을 통해 의존성을 받게되면 이를 해당 디렉토리에 캐시해며, 다음 배포 떄 같은 의존성은 다시 받지 않도록 생략
cache:
 directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

# master 브랜치에 push 되었을 때 수행하는 명령어
## 여기선 프로젝트 내부에 둔 gradlew을 통해 'clean & build'를 수행
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notification:
 email:
  recipients:
   - yolip51@gmail.com
