#AWS CodeDeploy 설정
version: 0.0 # 프로젝트 버전이 아니기 때문에, 0.0 외에 다른 버전을 사용 시 오류 발생
os: linux
files:
  - source: / #S3 버킷에서 복사할 파일의 위치
    destination: /home/ec2-user/app/travis/build/

# CodeDeploy에서 바로 'deploy.sh'를 실행시킬 수 없다. 따라서 우회방법으로 'deploy.sh'를 실행하는 'execute-deploy.sh'파일을 실행
# 기타 yml들과 마찬가지로, 'execute-deploy.sh'ㅇ
hooks:
  AfterInstall: # 배포가 끝나면 아래의 명령어를 실행
    - location: execute-deploy.sh
      timeout: 180